### ISSUE TITLE
Question on graphs

### ISSUE THREAD

**Issue by kalyani7195** [bartwojcik/D2DMoE#1]
Hi! Thanks for the great work!
I was trying to reproduce your pipeline and get some output plots like these -- 
<img width="900" alt="image" src="https://github.com/user-attachments/assets/66ca4464-9bab-49e0-83d4-3f8e5799cff1" />
I was wondering if this is an expected output becuase my understanding was that the FLOPs should vary as the tau varies -- that's how the plots also look like in the paper.

Any help regarding this would be very appreciated. thank you!
Kalyani

**Comment by bartwojcik** [comment]
Indeed our FLOPs counting code was incorrect for language generation models. The bug was probably introduced by me when merging code from different branches before code release. Newest commit bf946f6 should fix that now, please pull, test and confirm if it works.

**Comment by kalyani7195** [comment]
Thank you so much for looking into it and  fixing the issue -- will try that out and reach out to you if I have any other questions!

Best,
Kalyani
